### ISSUE TITLE
When user submits solution to exercise should they do "git add/commit/push origin" instead of classic submit?

### ISSUE THREAD

**Issue by constandrei** [iampava/frontend.ro#5]
This would be useful to ease their introduction with industry-relevant Git flows.

**Comment by iampava** [comment]
Great idea! Will definitely do!

**Comment by iampava** [comment]
Instead of a `Submit` button at the end of an exercise, let's have a mock CLI where the user will need to type 3 commands:

`git add .`
`git commit -m "Some commit message"`
`git push`

Why? I think it's important to familiarize people with Git concepts. Soo, if instead of a simple button, we require them to write those commands, it will be easier to use Git when they need to.

So, let's build a custom React Component, which handles all of this internally, and by using a prop-callback, notifies it's parent when everything is actually done.

**Comment by andreeatoma** [comment]
I will build this custom React Component which handles the CLI for Git.
